package com.codecrafthub.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.Instant;
import java.time.LocalDate;

/**
 * Represents a course in the CodeCraftHub application.
 */
@JsonIgnoreProperties(ignoreUnknown = false)
public class Course {

    /**
     * The ID is generated by the service.
     */
    @JsonProperty(value = "id")
    private Long id;

    /**
     * Course name is required and cannot be blank.
     */
    @NotBlank(message = "name is required")
    @JsonProperty("name")
    private String name;

    /**
     * Course description is required and cannot be blank.
     */
    @NotBlank(message = "description is required")
    @JsonProperty("description")
    private String description;

    /**
     * The Java field uses camelCase, but JSON uses target_date.
     */
    @NotNull(message = "target_date is required")
    @JsonProperty("target_date")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate targetDate;

    /**
     * Status must be one of the values defined by CourseStatus.
     */
    @NotNull(message = "status is required")
    @JsonProperty("status")
    private CourseStatus status;

    /**
     * The timestamp is generated by the server.
     */
    @JsonProperty(value = "created_at")
    private Instant createdAt;

    /**
     * Required by Jackson when reading JSON.
     */
    public Course() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getTargetDate() {
        return targetDate;
    }

    public void setTargetDate(LocalDate targetDate) {
        this.targetDate = targetDate;
    }

    public CourseStatus getStatus() {
        return status;
    }

    public void setStatus(CourseStatus status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}