package com.codecrafthub.service;

import com.codecrafthub.exception.CourseNotFoundException;
import com.codecrafthub.exception.DataFileException;
import com.codecrafthub.model.Course;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Service layer responsible for course operations and JSON file storage.
 */
@Service
public class CourseService {

    /**
     * The required JSON file name.
     *
     * This file is created in the application's working directory.
     */
    private static final Path DATA_FILE = Paths.get("courses.json");

    private final ObjectMapper objectMapper;

    public CourseService() {
        /*
         * ObjectMapper is Jackson's main JSON processing class.
         *
         * JavaTimeModule allows Jackson to process:
         * - LocalDate
         * - Instant
         */
        this.objectMapper = new ObjectMapper();
        this.objectMapper.registerModule(new JavaTimeModule());

        /*
         * Make dates and timestamps readable instead of numeric timestamps.
         */
        this.objectMapper.findAndRegisterModules();
        this.objectMapper.disable(com.fasterxml.jackson.databind.SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

        createFileIfMissing();
    }

    /**
     * Returns every course in the JSON file.
     */
    public synchronized List<Course> getAllCourses() {
        return readCourses();
    }

    /**
     * Returns one course or throws a 404-compatible exception.
     */
    public synchronized Course getCourseById(Long id) {
        return readCourses()
                .stream()
                .filter(course -> course.getId().equals(id))
                .findFirst()
                .orElseThrow(() -> new CourseNotFoundException(id));
    }

    /**
     * Creates a new course.
     *
     * The ID and createdAt timestamp are generated by the server.
     */
    public synchronized Course createCourse(Course course) {
        List<Course> courses = readCourses();

        long nextId = courses.stream()
                .map(Course::getId)
                .filter(id -> id != null)
                .max(Comparator.naturalOrder())
                .orElse(0L) + 1;

        course.setId(nextId);
        course.setCreatedAt(Instant.now());

        courses.add(course);
        writeCourses(courses);

        return course;
    }

    /**
     * Updates all editable fields of an existing course.
     *
     * The original ID and createdAt timestamp are preserved.
     */
    public synchronized Course updateCourse(Long id, Course updatedCourse) {
        List<Course> courses = readCourses();

        Course existingCourse = courses.stream()
                .filter(course -> course.getId().equals(id))
                .findFirst()
                .orElseThrow(() -> new CourseNotFoundException(id));

        existingCourse.setName(updatedCourse.getName());
        existingCourse.setDescription(updatedCourse.getDescription());
        existingCourse.setTargetDate(updatedCourse.getTargetDate());
        existingCourse.setStatus(updatedCourse.getStatus());

        writeCourses(courses);

        return existingCourse;
    }

    /**
     * Deletes a course by ID.
     */
    public synchronized void deleteCourse(Long id) {
        List<Course> courses = readCourses();

        boolean removed = courses.removeIf(course -> course.getId().equals(id));

        if (!removed) {
            throw new CourseNotFoundException(id);
        }

        writeCourses(courses);
    }

    /**
     * Creates courses.json if it does not already exist.
     */
    private void createFileIfMissing() {
        try {
            if (Files.notExists(DATA_FILE)) {
                Files.writeString(DATA_FILE, "[]");
            }
        } catch (IOException exception) {
            throw new DataFileException(
                    "Could not create courses.json",
                    exception);
        }
    }

    /**
     * Reads the entire JSON array from courses.json.
     */
    private List<Course> readCourses() {
        try {
            createFileIfMissing();

            String json = Files.readString(DATA_FILE);

            /*
             * An empty file is treated as an empty course list.
             */
            if (json.isBlank()) {
                return new ArrayList<>();
            }

            List<Course> courses = objectMapper.readValue(
                    json,
                    new TypeReference<List<Course>>() {
                    });

            /*
             * Protect the rest of the application from a null JSON array.
             */
            return courses != null ? courses : new ArrayList<>();

        } catch (IOException | RuntimeException exception) {
            /*
             * RuntimeException also catches invalid JSON parsing errors.
             */
            throw new DataFileException(
                    "Could not read courses.json",
                    exception);
        }
    }

    /**
     * Writes all courses to courses.json.
     *
     * A temporary file is written first. It is then moved over the original
     * file to reduce the risk of leaving a partially written JSON file.
     */
    private void writeCourses(List<Course> courses) {
        Path temporaryFile = Paths.get("courses.json.tmp");

        try {
            String json = objectMapper
                    .writerWithDefaultPrettyPrinter()
                    .writeValueAsString(courses);

            Files.writeString(temporaryFile, json);

            try {
                Files.move(
                        temporaryFile,
                        DATA_FILE,
                        StandardCopyOption.REPLACE_EXISTING,
                        StandardCopyOption.ATOMIC_MOVE);
            } catch (AtomicMoveNotSupportedException exception) {
                /*
                 * Some operating systems do not support atomic moves.
                 * A normal replacement is used as a fallback.
                 */
                Files.move(
                        temporaryFile,
                        DATA_FILE,
                        StandardCopyOption.REPLACE_EXISTING);
            }

        } catch (IOException | RuntimeException exception) {
            try {
                Files.deleteIfExists(temporaryFile);
            } catch (IOException ignored) {
                // The original file operation error is more important.
            }

            throw new DataFileException(
                    "Could not write courses.json",
                    exception);
        }
    }
}